main/urls.py
from django.urls import path

from main import views

namespace = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('products/', views.products_list, name='products-list'),
    path('products/site/<str:site>/', views.products_list, name='products-list-filtered'),
    path('products/brand/<str:brand>/', views.products_list, name='products-list-filtered-brand'),
    path('products/site/<str:site>/brand/<str:brand>/', views.products_list, name='products-list-filtered-both'),
    path('product/<int:product_pk>/', views.product_detail, name='product-detail'),
]


handler404 = views.custom_page_not_found

project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

from project.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'))),
]

if DEBUG:
    urlpatterns += debug_toolbar_urls()

main/models.py
from django.db import models


class Product(models.Model):
    site = models.CharField(max_length=255, verbose_name='Sayt', db_index=True)
    name = models.CharField(max_length=255, verbose_name='Noutbuk nomi', db_index=True)
    price = models.IntegerField(verbose_name='Narxi')
    url = models.URLField(max_length=500, unique=True, verbose_name='URL')
    image_url = models.URLField(max_length=500, blank=True, null=True, verbose_name='Rasm URL')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')
    updated_at = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")

    class Meta:
        db_table = 'products'
        verbose_name = 'Noutbuk'
        verbose_name_plural = 'Noutbuklar'
        unique_together = ('url', 'name')

    def __str__(self):
        return f'{self.name} ({self.site})'

main/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, render

from main.models import Product


def home(request):
    lastest_products = Product.objects.all().order_by('-created_at')[:8]
    context = {
        'title': 'Bosh sahifa',
        'lastest_products': lastest_products,
    }
    return render(request, 'main/index.html', context=context)


def products_list(request, site=None, brand=None):
    if query := request.GET.get('query'):
        words = query.split()
        filters = Q()
        for word in words:
            filters &= Q(name__icontains=word)
        products = Product.objects.filter(filters).order_by('price')
    else:
        products = Product.objects.all()

    if site:
        products = products.filter(site=site).order_by('price')
    if brand:
        products = products.filter(name__icontains=brand).order_by('price')

    brands = ['Apple', 'Samsung', 'Huawei', 'Lenovo', 'HP', 'Dell', 'Asus', 'Acer', 'MSI']
    paginator = Paginator(products, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    sites = Product.objects.values_list("site", flat=True).distinct()
    context = {
        'title': 'Mahsulotlar',
        'sites': sites,
        'products': page_obj,
        'brands': brands,
        'selected_site': site,
        'selected_brand': brand,
        'page_obj': page_obj
    }
    return render(request, 'main/products_list.html', context=context)


def product_detail(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    context = {
        'title': 'Noutbuk',
        'product': product,
    }
    return render(request, 'main/product_detail.html', context=context)


def about(request):
    context = {
        'title': 'Biz Xaqimizda',
    }
    return render(request, 'main/about.html', context=context)


def custom_page_not_found(request, exception):
    return render(request, '404.html', status=404)

main/templates/main/about.html
{% extends 'base.html' %}

{% load static %}

{% block active_class %}active{% endblock %}

{% block content %}
    <div class="section padding_layout_1">
    <div class="container">
        <div class="row">
        <div class="col-md-12">
            <div class="full">
            <div class="main_heading text_align_center">
                <h2>Bu sayt xaqida</h2>
            </div>
            </div>
        </div>
        </div>
        <div class="row about_blog">
        <div class="col-lg-6 col-md-6 col-sm-12 about_cont_blog">
            <div class="full text_align_left">
            <h3>Biz nima qilamiz</h3>
            <p>Bizning saytimiz turli xil onlayn-do'konlardan yig'ilgan noutbuklarning qulay agregatoridir. 
                Modellarni tezda taqqoslash va eng yaxshi variantni tanlashga yordam berish uchun biz avtomatik ravishda joriy narxlar va
                xususiyatlarini kuzatamiz. Bir joyda ajoyib takliflarni topib, vaqt va pulni tejang!</p>
            <ul>
                <li><i class="fa fa-check-circle"></i>O'yin uchun noutbuklar</li>
                <li><i class="fa fa-check-circle"></i>Ofis uchun noutbuklar</li>
                <li><i class="fa fa-check-circle"></i>Og'ir dasturlar bilan ishlash uchun noutbuklar</li>
            </ul>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 about_feature_img padding_right_0">
            <div class="full text_align_center"> <img class="img-responsive" src="{% static 'images/it_service/post-07.jpg' %}" alt="#" /> </div>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block active_class %}active{% endblock %}

{% block content %}
    <div class="section padding_layout_1">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="full">
            <div class="main_heading text_align_center">
              <h2>oxirgi qo'shilgan noutbuklar</h2>
            </div>
          </div>
        </div>
      </div>
      
      <div class="row">
        {% for product in lastest_products %}
          <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 margin_bottom_30_all">
            <div class="product_list">
              <div class="product_img"> <img class="img-responsive" src="{{ product.image_url }}" alt=""> </div>
              <div class="product_detail_btm">
                <div class="center">
                  <h4><a href="{% url 'main:product-detail' product.pk %}">{{ product.name }}</a></h4>
                </div>
                <div class="product_price">
                  <p>
                    <span class="new_price">{{ product.price|floatformat:2|intcomma }}</span>
                    <b> UZS </b>
                  </p>
                </div>                
              </div>
            </div>
          </div>  
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/product_detail.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block content %}
  <div class="row">
    <div class="col-xl-6 col-lg-12 col-md-12">
      <div class="product_detail_feature_img hizoom hi2">
        <div class='hizoom hi2'> <img src="{{ product.image_url }}" alt="#"  width="400" height="400"/> </div>
      </div>
    </div>
    <div class="col-xl-6 col-lg-12 col-md-12 product_detail_side detail_style1">
      <div class="product-heading">
        <h2>{{ product.site }}</h2>
      </div>
      <div class="product-detail-side"><span class="new-price"> <span> {{ product.price|floatformat:2|intcomma }}</span> <b>Uzs</b> </div>
      <div class="detail-contant">
        <p>{{ product.name }}<br>
          <a href={{ product.url }}><button type="submit" class="btn sqaure_bt">Sotib olish uchun</button></a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/products_list.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}


{% block content %}
<div class="bg_load"> <img class="loader_animation" src="{% static 'images/loaders/loader_1.png' %}" alt="#" /> </div>

<div class="section padding_layout_1 product_list_main">
  <div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% if  products %}
                    {% for product in products %}
                        <div class="col-md-4 col-sm-6 col-xs-12 margin_bottom_30_all">
                            <div class="product_list">
                            <div class="product_img"> 
                                {% if product.image_url %}
                                    <a href="{% url 'main:product-detail' product.pk %}">
                                        <img class="img-responsive" src="{{ product.image_url }}" >
                                    </a>
                                {% else %}
                                    <a href="{% url 'main:product-detail' product.pk %}">
                                        <img class="img-responsive" src="{% static 'images/not_found.webp' %}" alt="Rasm yo'q">
                                    </a>
                                {% endif %}
                            </div>
                            <div class="product_detail_btm">
                                <div class="center">
                                <h4><a href="{% url 'main:product-detail' product.pk %}">{{ product.name|truncatechars:80 }}</a></h4>
                                </div>
                                <div class="product_price">
                                    <p><span class="new_price">{{ product.price|floatformat:2|intcomma }}</span><b> Uzs</b></p>
                                </div>
                            </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h3>Hech narsa topilmadi</h3>
                {% endif %}
            </div>
        </div>


        <div class="col-md-3">
            <div class="side_bar">
                <div class="side_bar_blog">
                    <h4>Onlayn do'konlar </h4>
                    <div class="categary">
                        <ul>
                            <li><a href="{% url 'main:products-list' %}" class="{% if not selected_brand and not selected_site %}active{% endif %}">Hammasi</a></li>
                            {% for site in sites %}
                                <li>
                                    <a href="{% url 'main:products-list-filtered' site=site %}" class="{% if site == selected_site %}active{% endif %}">
                                        <i class="fa fa-angle-right"></i> {{ site }}
                                    </a>
                                </li>
                            {% endfor %}
                            

                        </ul>
                    </div>
                </div>
                <div class="side_bar_blog">
                    <h4>Brand </h4>
                    <div class="categary">
                        <ul>
                            {% for brand in brands %}
                                <li>
                                    <a href="{% if selected_site %}{% url 'main:products-list-filtered-both' site=selected_site brand=brand %}{% else %}{% url 'main:products-list-filtered-brand' brand=brand %}{% endif %}" class="{% if brand == selected_brand %}active{% endif %}">
                                        <i class="fa fa-angle-right"></i> {{ brand }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div> 
            </div>
        </div>

        
        {% if page_obj.paginator.num_pages > 1 %}
            <nav aria-label="Navigatsiya">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="Boshi">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Avvalgi">
                                <span aria-hidden="true">&lsaquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">&laquo; </span>
                        </li>
                        <li class="page-item disabled">
                            <span class="page-link">&lsaquo;</span>
                        </li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                        {% if num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                            {% if page_obj.number == num %}
                                <li class="page-item active" aria-current="page">
                                    <span class="page-link">{{ num }}</span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Keyingi">
                                <span aria-hidden="true">&rsaquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Oxirgi">
                                <span aria-hidden="true"> &raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">&rsaquo;</span>
                        </li>
                        <li class="page-item disabled">
                            <span class="page-link"> &raquo;</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
  </div>
</div>
{% endblock %}